mediachain/concat

package.json
So it turns out that dialing from go to javascript was failing because libp2p wasn't sending the public key from go.  That got fixed [a few days ago](https://github.com/libp2p/go-libp2p/commit/65273ab3e7fd033887f5276fdb51df4028d8ebe8), so this bumps libp2p to the latest published version.
Now I can ping javascript nodes from go!
=> bump libp2p to 3.5.3 to fix dial bug (missing public key)

package.json
Still waiting for the ecc keys to bubble up in libp2p, but a bump is a bump.
=> version bump libp2p to 3.5.4

mcnode/api.go, mcnode/db.go, mcnode/proto.go
SQLite tuning:
- tune concurrent write performance by disabling the connection pooling (lock contention!) and enabling Write-Ahead Logging
/ping protocol:
- Ensure there is a connection to the directory before trying to open a stream
- Add a 30s timeout to /ping; one day it may become a request parameter (and be common with other requests that access remote resources)
=> A couple of fixes: SQLite tuning and pings

mc/query/query.go, mcnode/api.go, mcnode/db.go, mcnode/node.go
So in order to not kill concurrent write performance, sqlite needs to be used with conn pooling disabled.
Unfortunately this causes Delete to deadlock, as it is using a streaming query to fetch the ids for deletion.
On the other hand simply fetching all the ids together in memory can lead to problems for large datasets (too much memory).
So in order to have our cake and eat it too (at least most of it), delete operates in batches.
The ugly side is that we can now have partial deletes, which are distinguished by both the returned count being >0, and the error being non-nil.
In other changes, the node has stopped being chatty in statement publication.
=> Fix Delete deadlock when connection pooling is disabled

mc/message.go, mcnode/api.go, mcnode/main.go, mcnode/node.go, mcnode/proto.go, proto/dir.pb.go, proto/node.pb.go, proto/node.proto, proto/stmt.pb.go, proto/stmt.proto
Implements the remote query protocol, with associated REST api endpoint.
Closes #22 
Notes:
- There is an ABI change in stmt.proto: StatementBody is now a first class type to allow query results
- Remote errors in the query are not propagated in the stream, just logged; perhaps we need to change the query stream protocol to emit error objects in the stream (applies to StatementDb.QueryStream as well)
Example:
```
$ curl http://127.0.0.1:9004/id
Qme1ypbSE8vvuSSeZ5YWTRDDbULUjuTeNJ6QCyijxdmaJt
$ curl -H "Content-Type: application/text" -d 'SELECT COUNT(id) FROM *' http://127.0.0.1:9004/query
0
$ curl -H "Content-Type: application/text" -d 'SELECT COUNT(id) FROM *' http://127.0.0.1:9004/query/QmWwnVop4hHB3K6z2vuUgU9rh5VrDwMnwuiP9LZew7NzUK
1000
$ curl -H "Content-Type: application/text" -d …
```
=> Remote Query Protocol

mc/query/query.go, mcnode/api.go, mcnode/db.go, mcnode/main.go, mcnode/node.go, mcnode/proto.go
Adds support for merging remote datasets, by virtue of a statement select query, exposed through the `/merge` endpoint.
Closes #25 
Example:
```
$ curl -H "Content-Type: application/text" -d 'SELECT COUNT(id) FROM *' http://127.0.0.1:9004/query
0
$ curl -H "Content-Type: application/text" -d 'SELECT * FROM * LIMIT 5' http://127.0.0.1:9004/merge/QmWwnVop4hHB3K6z2vuUgU9rh5VrDwMnwuiP9LZew7NzUK
5
$ curl -H "Content-Type: application/text" -d 'SELECT * FROM * LIMIT 10' http://127.0.0.1:9004/merge/QmWwnVop4hHB3K6z2vuUgU9rh5VrDwMnwuiP9LZew7NzUK
5
$ curl -H "Content-Type: application/text" -d 'SELECT * FROM * LIMIT 11' http://127.0.0.1:9004/merge/QmWwnVop4hHB3K6z2vuUgU9rh5VrDwMnwuiP9LZew7NzUK
1
$ curl -H "Content-Type: application/text" -d 'SELECT COUNT(id) FROM *' http://127.0.0.1:9004/query
11 …
```
=> Remote merges

mcnode/db.go
It's the one thing we really want to index I think, so this creates an index when creating the database.
You'll want to rebuild your db; either wipe it or manually open it with sqlite and create the index.
=> Add index for namespaces in the db

mc/util.go, mcdir/main.go, mcnode/api.go, mcnode/main.go, mcnode/node.go, mcnode/proto.go
Performs the necessary work to support the public Internet.
Closes #11 
Summary:
- mcnode and mcdir now bind to INADDR_ANY
- mcnode allows NAT configuration: 
- none; default, no NAT
- auto; use the libp2p NATPortMap service
- manual; uses a user specified public address
- mcnode is selective in how it reports addresses to the directory:
- if the directory is on localhost, then it reports its localhost address; supports testing
- if the directory is on a private network, then it will publish its routable addresses
- if the directory is on a publicly routable network, then it will only report public addresses (if any)
- mcnode configuration is now persisted to disk.
Tested on laptop and ec2.
=> Public Network Connectivity

mcnode/main.go
I've been working on getting integration tests setup between aleph & concat, by running a concat node in a docker container.  To get it to work, I need to be able to have the HTTP API server listen on an external IP instead of localhost, so this adds a `-b` flag that lets you bind the API server to 0.0.0.0 (or whatever)
=> mcnode: add bind address cli flag for http api

build.sh, install.sh, mc/util.go, mcnode/api.go, mcnode/db.go, mcnode/ds.go, mcnode/main.go, mcnode/node.go, mcnode/proto.go, proto/dir.pb.go, proto/node.pb.go, proto/node.proto, setup.sh
Closes #36 
- Implements the datastore for statement metadata with rocksdb.
- Provide a `/data/put` and `/data/get` API endpoints for storing/retrieving metadata objects.
- Implement the `/mediachain/node/data` protocol for retrieving statement metadata from remote peers.
- Merge statement metadata along with statements in the merge implementation.
Note:
There is a minor change in the remote query protocol, as the end/error messages where refactored to be reused in the data protocol.
Datastore API details: 
- `/data/put` accepts a batch of DataObjects, which are json objects with a data field containing the data base-64 encoded, and returns a stream of object keys (which are B58-encoded SHA256 multihashes)
- `/data/get/{objectId}` retrieves a data object by its key or 404s.
Example:
```
$ …
```
=> Datastore and statement metadata

mcdir/main.go, mcnode/db.go, mcnode/main.go, setup.sh
A little leisurely Saturday morning hacking:
- Try to tune SQLDB.PutBatch by moving statement marshalling out of the transaction, which minimizecritical section time for concurrent writes -- Turns out this actually slows down ingestion, most likely because of blown cpu caches.
- Default the mcnode and mcdir home directories to ~/.mediachain/mc{node,dir} [#43]
Note: we have acquired a new unvendored dependency on go-homedir.
=> Some small fixes

README.md, mc/query/stmt.go, mcnode/proto.go
Last merge for v1.0:
Implement the necessary logic to support merging multi-statements (compound or envelopes) so that v1.0 release mcnode is forward compatible.
=> Future Proofing: Support merging multi-statements

README.md, mcnode/api.go, mcnode/main.go, mcnode/proto.go
Extends the `/publish/ns` endpoint with a `/publish/ns/N`, which publishes compound statements in groups of N [#62]
Also fixes a missing error check in mergeDataImpl.
Demo:
```
$ wc -l /tmp/batch100 
100 /tmp/batch100
$ head -5 /tmp/batch100
{"object": "QmSiRz7p3y7Y3fYcvxdHRv2gAmKaQ21tjrKMu3Cgq215uj", "refs": ["abc"], "tags": ["test"]}
{"object": "QmTJqrdXaxkrR3rW4VMMzPVkzHZrnHoDgY1WnhVxhQa3Sa", "refs": ["abc"], "tags": ["test"]}
{"object": "QmZw5rJokTsayoKi1rDehFS1WfefsoXyFXVzuMJwt8baJj", "refs": ["abc"], "tags": ["test"]}
{"object": "QmSiRz7p3y7Y3fYcvxdHRv2gAmKaQ21tjrKMu3Cgq215uj", "refs": ["abc"], "tags": ["test"]}
{"object": "QmTJqrdXaxkrR3rW4VMMzPVkzHZrnHoDgY1WnhVxhQa3Sa", "refs": ["abc"], "tags": ["test"]}
$ curl -s -H "Content-Type: application/json" -d "@/tmp/batch100" …
```
=> Compound Statement publishing

mc/util.go, mcdir/main.go, mcnode/proto.go
Changes in mc.NewHost:
- client owns the context used by the swarm network object
- allow nil address for delayed binding.
Change in mcnode/proto
- Adds a delay in the offline->online->public transition when NATConfig = auto, so that port mapping can complete before the first directory registration attempt.
=> Small networking fixes

.gitignore, .travis.yml, package.sh
This sets up automatic deployment to github releases when you tag a commit with a tag starting with `v`
- adds `package.sh` to generate tarballs in `./dist`
- filenames are of the form `mcnode-${version}-${os}-${arch}.tgz`
- on linux, runs `strip` before generating the main tarball, and also makes a `-unstripped` variant
updates to travis.yml:
- cache go dependencies between builds (huge speed improvement)
- build for osx and linux
- deploy to github releases if commit is tagged and tag starts with `v`
One quirk is that the releases are marked as public (taken out of Draft status) when the upload completes, and it's not aware that we're building for more than one OS.  Since mac builds tend to get stuck in the queue for a while, releases will probably be lacking mac binaries for a little …
=> Automatic packaging and deployment for tagged releases

mcnode/proto.go
More robust handling of connect/lookup logic in mcnode:
Decide on whether to lookup a peer based on the connectivity as reported by libp2p.
=> Use connectedness as reported by libp2p when deciding to lookup/connect

mc/nat.go
- Use `ifconfig.mediachain.io` with fallback to `ifconfig.co` in `mc.GetPublicIP`
- Handle request errors and check validity of response
Closes #83
=> More robust ifconfig

mc/identity.go
it's the prefered nomenclature.
=> It's the Peer ID, so let's not confuse users.

mc/util.go, mcnode/api.go, mcnode/ds.go, mcnode/gc.go, mcnode/main.go, mcnode/node.go
Closes #64 
Implements datastore garbage collection with direct iteration.
Implementation Notes:
- datastore iterators require flushing the db to work reliably
- a temporary db is used for storing the live object index
- `/data/compact` api endpoint for manual compaction; gc triggers it if it deletes any objects, but it's also useful on its own right
- `/data/sync` api endpoint: the WAL seems to be using some dark space in linux/ext4 (not visible in ls, but visible in du) following merges, but it seems to be bounded by the log size. Flushing the datastore through the endpoint immediately reclaims this space,
- `/data/keys` api endpoint which dumps the keys for all objects in the datastore.
Example:
```
$ du --si /mnt/ssd2/data/
193k    /mnt/ssd2/data/
$ mcclient status online
status set …
```
=> Datastore Garbage Collection

mcnode/node.go
Closes #93 
The auth map is normally initialized by loadConfig, but in the absence of a config file it will be left uninitialized.
This creates the map on demand if it's not initialized.
=> Fix crash from uninitialized auth map set

mcnode/ds.go, setup.sh
A commit to gorocksdb broke the embedded build:
https://github.com/tecbot/gorocksdb/issues/71
This points us at a mediachain fork with the problematic commit
reverted.  We can either keep our fork in sync with the upstream,
or switch back once they incorporate the fix.
=> Use fork of gorocksdb to avoid build error

mc/util.go, mcnode/api.go, mcnode/main.go, mcnode/net.go
- Adds `/net/conns` api hook for retrieving all actively connected peers, formatted as multiaddr handles.
- Adds `/net/addr/{peerId}` api hook for retrieving known/cached peer addresses
- Fixes FormatHandle to format canonically in the naked id case.
- Changes the lookup cache TTL to 10min.
Example:
```
$ curl http://localhost:9002/net/conns
$ mcclient status online
status set to online
$ curl http://localhost:9002/net/conns
/ip4/104.236.76.40/tcp/4001/p2p/QmSoLV4Bbm51jM9C4gDYZQ9Cy3U6aXMJDAbzgu2fzaDs64
/ip4/128.199.219.111/tcp/4001/p2p/QmSoLSafTMBsPKadTEgaXctDQVcqN88CNLHXMkTNwMKPnu
/ip4/104.236.179.241/tcp/4001/p2p/QmSoLPppuBtQSGwKDZT2M73ULpjvfd3aZ6ha4oFGL1KrGM
/ip4/178.62.158.247/tcp/4001/p2p/QmSoLer265NRgSp2LA3dPaeykiS1J6DifTC88f5uVQKNAd
$ mcclient lookupPeer …
```
=> Net connections and small fixes

mcnode/api.go, mcnode/main.go
Implements `/data/get` for batch object retrieval
Closes #91 
The endpoint accepts a newline separated list of object keys, and returns a stream of data objects.
If a key is not stored in the datastore, then the returned data object will have a null data field.
If an errors occurs (eg a bad key or a datastore error), then the stream ends with a StreamError.
Example:
```
$ cat /tmp/some-keys
QmYGRQYmWC3BAtTAi88mFb7GVeFsUKGM4nm25SBUB9vfc9
QmeFJSTPKSEiNqebxZvYcduWH8UBmxqNq724gHEQnxV5D1
$ curl -i --data-binary "@/tmp/some-keys" http://localhost:9002/data/get
{"data":"pmckc2NoZW1heCdodHRwOi8vanNvbi1zY2hlbWEub3JnL2RyYWZ0LTA0L3NjaGVtYSNrZGVzY3JpcHRpb254Jk1lZGlhY2hhaW4gTGFicyBpbmRleGVyIGltYWdlIG1ldGFkYXRhZHNlbGakZnZlbmRvcnVpby5tZWRpYWNoYWluLmluZGV4ZXJkbmFtZWVpbWFnZWZmb3JtYXRqanNvbnNjaGVtYWd2ZXJzaW …
```
=> Datastore batch object retrieval api

mcnode/api.go, mcnode/net.go, mcnode/node.go
Closes #77 
Implementation Details:
- dir configuration takes a list of handles, with auto-migration of old config files (on first config change).
- dir lookups start in parallel, with first response winning.
- dir listings happen in parallel and aggregate results from both peers.
Some changes to timeouts:
- sets dir listing operations to 10s, so that we can get results timely even if some dirs are badly failed.
- similarly sets an internal 10s timeout for directory lookup, so that we can fallback to the dht in timely fashion.
=> Multiple directory support in mcnode

package.json
Fixes ticker leak; see https://github.com/libp2p/go-libp2p-kad-dht/pull/44
=> Update go-libp2p-kad-dht to 2.4.9

mcnode/net.go
this tunes the directory lookup timeout to 5s, so that a single directory failure (or libp2p acting mysterious and failing to connect) will not hold up a dht lookup for a full 10s in the case of unregistered nodes.
Could be even lower, maybe 2-3s, but I would rather be conservative with this; 5s is a potentially slow lookup from the dht, but not intolerably so.
=> Reduce directory lookup timeout

mc/query/stmt.go
This fixes a subtle issue with duplicate wkis in compound statements: 
It is possible for a compound statement to include simple statements which refer to the same wki, which would be included multiple times in the list returned by `mcq.StatementRef`.
As a result, the same statement would be mapped to the same wki multiple times in the Refs table. 
This would create garbage in the db and have the unfortunate side effect of having the same statement appear multiple times in a query result set even when querying for a single wki.
The PR fixes this by constructing a set for compound statements, which deduplicates the wkis.
Measurements indicate no performance penalty for compound statement processing.
PS: Also added dedup for simple statements, to protect from faulty publishers who don't …
=> Deduplicate wkis in mcq.StatementRefs for compound statements

mc/query/eval.go, mc/query/query_test.go, mc/query/stmt.go, mcnode/db.go
Follow up to #107 
Now that the simple statements are also deduplicated, there is nothing to gain from an interface that constructs a list from an intermediate set.
This changes `mcq.StatementRefs` to return the set directly
=> Return reference set from mcq.StatementRefs

mcnode/api.go, mcnode/net.go, mcnode/node.go
Improving on the situation with the timeouts and lookups:
- doLookup now does both dir and dht lookups in parallel (instead of first trying the directories and then falling back to the dht) and uses the first available result.
- api timeouts for simple requests are reduced to 10s
- remove netLookup api timeout, as timeouts are explicitly set in the lookup.
=> Parallelize dht and dir lookups, more reasonable timeouts

package.sh
This just adds mcid to the `package.sh` script that make our release tarballs.  Travis is setup to upload `dist/*.tgz` as part of the release, so it should get uploaded automatically.
=> mcid: make mcid tarball in release package script

proto/json.go
Injects the json.Marshaller interface to the protobuf generated code, so that they can be properly marshalled to JSON using jsonpb.
It is only used for statements so far, as they are the only protobuf objects directly translated to json.
Manifests will also use the trick once they are integrated in mcnode/mcdir, in a subsequent PR.
The change is obvious in query output.
Compare:
```
mcclient query "SELECT * FROM images.dpla LIMIT 1"
{
"id": "4XTTM4K8sqTb7xYviJJcRDJ5W6TpQxMoJ7GtBstTALgh5wzGm:1478267497:1",
"publisher": "4XTTM4K8sqTb7xYviJJcRDJ5W6TpQxMoJ7GtBstTALgh5wzGm",
"namespace": "images.dpla",
"body": {
"Body": {
"Simple": {
"object": "QmeFJSTPKSEiNqebxZvYcduWH8UBmxqNq724gHEQnxV5D1",
"refs": [
"dpla_1ff6b36174426026847c8f8ca216ffa9"
],
"deps": [ …
```
=> Use jsonpb for JSON marshalling Statements

mc/version.go, mcdir/main.go, mcnode/api.go, mcnode/main.go, mcnode/net.go, mcnode/node.go, mcnode/proto.go, package.json
Further improves on our IPFS interoperability [#78]:
- Sets the ClientVersion to identify our nodes through the `/ipfs/identify` protocol; new in libp2p-4.3.1
- Integrates the libp2p PingService, so that nodes can ping/pong using the ipfs protocol and deprecates the `/mediachain/node/ping` protocol
- New net api hooks
- `/net/ping/{peerId}` to ping using the ping service
- `/net/identify/{peerId}` for dumping the information collected for a peer by the libp2p IdentifyService
Examples:
```
$ mcclient id QmSbgwkKxtrBFDoGGwoKqH7soYiL64xpMK5oEYdiRnQGJp
Peer ID: QmSbgwkKxtrBFDoGGwoKqH7soYiL64xpMK5oEYdiRnQGJp
Publisher ID: 4XTTMGkYEx5trQX5VV32S82gguRMtVFQL5UDnZNHzyNEHKBeZ
Info: Mediachain Labs test node
$ ipfs swarm connect /ip4/54.242.130.109/tcp/9001/ipfs/QmSbgwkKxtrBFDoGGwoKqH7soYiL64xpMK5oEY …
```
=> More IPFS interop

mc/entity.go, mcid/main.go
Adds support for keybase users, through the `keybase:user` entity scheme [#14]
The entity key is distributed through kbfs with a public file named `mediachain.json`, which contains the output of `mcid id`.
=> Support keybase for entity keys

mc/version.go, mcdir/main.go, mcnode/main.go
Closes #120 
mcnode and mcdir: print version and exit with `-version`.
Note that we can't haz `--version`, as the golang `flag` package barfs if I use a dashed flag name...
Example:
```
$ mcnode -version
1.6-DEV
$ mcdir -version
1.6-DEV
```
=> version command 

.travis.yml, mcnode/ds.go
See https://github.com/mediachain/gorocksdb/pull/1
Basically, the latest rocksdb release (used by the embedded build in gorocksdb as of a few days ago), throws if you try to use `OptimizeForPointLookup` without setting the `allow_concurrent_memtable_write` option to `false`.  I added a setter for that option to our fork (and made a PR against the upstream repo: https://github.com/tecbot/gorocksdb/pull/75), and call it from `RocksDS.Open` to avoid the crash.
I haven't measured how this might impact ingestion performance, but it seems that the unsupported concurrent writes could lead to unpredictable crashes, so I guess it's a good thing to disable them.
=> Disable rocksdb concurrent writes

.travis.yml
In the latest gorocksdb mess scramble [#126], we ended up with gcc-6 as the compiler in travis.
This downgrades our travis build to use gcc-5, so that it matches development and set the baseline dependency to a non-exotic compiler.
=> gcc-5 please

mcnode/api.go, mcnode/dht.go, mcnode/main.go, mcnode/net.go, mcnode/node.go
The gist: ue use DHT provider records as a rendezvous mechanism:
- public peers provide the magic "/mediachain/node" key in the DHT
- the `/net/find` api allows us to discover peers though a provider query
Example:
```
$ curl http://127.0.0.1:9002/net/find
QmSbgwkKxtrBFDoGGwoKqH7soYiL64xpMK5oEYdiRnQGJp
$ mcclient id QmSbgwkKxtrBFDoGGwoKqH7soYiL64xpMK5oEYdiRnQGJp
Peer ID: QmSbgwkKxtrBFDoGGwoKqH7soYiL64xpMK5oEYdiRnQGJp
Publisher ID: 4XTTMGkYEx5trQX5VV32S82gguRMtVFQL5UDnZNHzyNEHKBeZ
Info: Mediachain Labs test node
```
=> Peer discovery through DHT rendezvous

mcnode/api.go, mcnode/db.go, mcnode/main.go, mcnode/node.go
Adds support for vacuuming the StatementDB: 
- Incremental vacuum can recover space following deletes. 
- Full vacuum recovers space and compacts the database. However, it needs lots of free space (as much as the live data set).
Implementation:
- New node databases are now created with `auto_vacuum=incremental`
- `/vacuum/incremental` performs an incremental vacuum, if it is enabled in the db. 
- `/vacuum/full` performs a full compacting vacuum, and it also sets the auto_vacuum mode to incremental for migrating existing node databases.
=> StatementDB vacuum support

mcnode/api.go, mcnode/main.go, mcnode/node.go, proto/json.go
Implements the `/import` API endpoint, which verifies and merges a stream of existing statements.
Closes #134 
Example:
```
$ mcclient id QmeiY2eHMwK92Zt6X4kUUC3MsjMmVb2VnGZ17DhnhRPCEQ
Peer ID: QmeiY2eHMwK92Zt6X4kUUC3MsjMmVb2VnGZ17DhnhRPCEQ
Publisher ID: 4XTTM4K8sqTb7xYviJJcRDJ5W6TpQxMoJ7GtBstTALgh5wzGm
Info: Metadata for CC images from DPLA, 500px, and pexels; operated by Mediachain Labs.
$ mcclient query -r QmeiY2eHMwK92Zt6X4kUUC3MsjMmVb2VnGZ17DhnhRPCEQ "SELECT * FROM images.500px LIMIT 1000" > /tmp/500px.json
$ curl --data-binary @/tmp/500px.json http://127.0.0.1:9002/import
1000
$ mcclient query "SELECT COUNT(*) FROM images.500px"
1000
$ mcclient query -r QmeiY2eHMwK92Zt6X4kUUC3MsjMmVb2VnGZ17DhnhRPCEQ "SELECT * FROM images.500px LIMIT 5000" > /tmp/more-500px.json
$ curl --data-binary …
```
=> Implement statement import for archive support

mcnode/dht.go
The bug has been fixed for a while now, but the comment was stll there.
=> Cosmetics: remove stale comment about dht leak
